language: java
jdk:
  - openjdk8

branches:
  only:
    - master
  allow_pr: true
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - openssl aes-256-cbc -K $encrypted_1b9375537de5_key -iv $encrypted_1b9375537de5_iv
    -in ymlfile.tar.enc -out ymlfile.tar -d

  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/pico-back.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: pico--bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: pico--bucket
    key: pico-back.zip

    bundle_type: zip
    application: pico

    deplyment_group: pico-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일알림
notifications:
  email:
    recipients:
      - sjj0077@naver.com