spring:
  datasource:
    url: jdbc:mysql://$DB_HOST:3306/pico?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: omenpico
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: prod
