server:
#  port: 8089
  prot: 80

spring:
  main:
    allow-bean-definition-overriding: true
  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update
#      ddl-auto : create
    properties :
      hibernate :
        format_sql : true
    generate-ddl : true
    database : mysql
    database-patform : org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false
      add-properties: false

  freemarker:
    cache: false
  thymeleaf :
    cache : false
    enabled : true
    prefix : classpath:/templates/
    suffix : .html

jwt:
  header: Autorization
  secret: $JWT_SECRET
  token-validity-in-seconds: 86400 # 하루


cloud:
  aws:
    credentials:
      accessKey: $AWS_ACCESS_KEY
      secretKey: $AWS_SECRET_KEY
    s3:
      bucket: pico--bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
